USE MediCareStore;
GO

-- Admin password: Admin@123 (bcrypt hash generated by backend seed)
-- User password: User@123

-- Categories
INSERT INTO Categories (Name, Slug, Description, Image, SortOrder) VALUES
(N'Máy đo huyết áp', 'may-do-huyet-ap', N'Thiết bị đo huyết áp chính xác', 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400&h=400&fit=crop', 1),
(N'Máy đo đường huyết', 'may-do-duong-huyet', N'Máy đo glucose và test strip', 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=400&h=400&fit=crop', 2),
(N'Khẩu trang y tế', 'khau-trang-y-te', N'Khẩu trang N95, khẩu trang y tế', 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=400&fit=crop', 3),
(N'Thiết bị oxy', 'thiet-bi-oxy', N'Máy tạo oxy, bình oxy y tế', 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=400&h=400&fit=crop', 4),
(N'Nhiệt kế y tế', 'nhiet-ke-y-te', N'Nhiệt kế điện tử, hồng ngoại', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop', 5),
(N'Xe lăn & hỗ trợ', 'xe-lan-ho-tro', N'Xe lăn, nạng, thiết bị phục hồi', 'https://images.unsplash.com/photo-1597075095404-5cc8e96bfcf0?w=400&h=400&fit=crop', 6);

-- Brands
INSERT INTO Brands (Name, Slug, Logo) VALUES
(N'Omron', 'omron', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Omron_Logo.svg'),
(N'Beurer', 'beurer', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Beurer_Logo.svg'),
(N'Philips', 'philips', 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Philips_logo_new.svg'),
(N'3M', '3m', 'https://upload.wikimedia.org/wikipedia/commons/3/3b/3M_logo.svg'),
(N'Yuwell', 'yuwell', 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_None.svg'),
(N'Microlife', 'microlife', 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_None.svg');

-- Products (sample - images use placeholder paths)
INSERT INTO Products (CategoryId, BrandId, Name, Slug, Description, Specifications, Price, SalePrice, Stock, SKU, IsFeatured, IsPopular, SoldCount, AverageRating, ReviewCount) VALUES
(1, 1, N'Máy đo huyết áp Omron HEM-7130', 'omron-hem-7130', 
 N'Máy đo huyết áp tự động tại nhà, màn hình LCD lớn, cảnh báo nhịp tim bất thường.',
 N'{"display":"LCD 3.5 inch","memory":"60 readings","power":"4x AAA","warranty":"3 years"}',
 1290000, 1090000, 50, 'OMR-7130', 1, 1, 320, 4.8, 45),
(1, 6, N'Máy đo huyết áp Microlife BP A2 Classic', 'microlife-bp-a2',
 N'Công nghệ MAM - đo 3 lần tự động, kết quả chính xác cao.',
 N'{"display":"LCD","memory":"99 readings","power":"4x AAA","warranty":"2 years"}',
 890000, NULL, 35, 'MIC-A2', 1, 0, 120, 4.5, 18),
(2, 5, N'Máy đo đường huyết Yuwell 580', 'yuwell-580',
 N'Đo nhanh 5 giây, cần máu 0.6μL, bộ nhớ 200 kết quả.',
 N'{"time":"5 seconds","memory":"200","sample":"0.6μL","warranty":"2 years"}',
 450000, 399000, 80, 'YW-580', 1, 1, 450, 4.7, 62),
(3, 4, N'Khẩu trang N95 3M 9210', '3m-n95-9210',
 N'Khẩm trang N95 chuẩn FDA, lọc 95% hạt bụi siêu nhỏ.',
 N'{"standard":"N95","pack":"20 pcs","filter":"95%","certification":"FDA"}',
 350000, 299000, 200, '3M-9210', 0, 1, 890, 4.6, 120),
(4, 3, N'Máy tạo oxy Philips EverFlo 5L', 'philips-everflo-5l',
 N'Máy tạo oxy 5L/phút, vận hành êm, tiết kiệm điện.',
 N'{"flow":"5 L/min","noise":"40 dB","power":"350W","warranty":"2 years"}',
 18500000, 16900000, 8, 'PHI-EV5', 1, 0, 25, 4.9, 8),
(5, 2, N'Nhiệt kế hồng ngoại Beurer FT 85', 'beurer-ft85',
 N'Đo không tiếp xúc, kết quả trong 1 giây, phù hợp trẻ em.',
 N'{"type":"Infrared","time":"1 second","range":"32-42.5°C","warranty":"2 years"}',
 650000, 549000, 60, 'BEU-FT85', 1, 1, 280, 4.8, 35),
(6, 5, N'Xe lăn điện Yuwell D05', 'yuwell-d05',
 N'Xe lăn điện gấp gọn, pin lithium, tốc độ 6km/h.',
 N'{"speed":"6 km/h","battery":"Lithium 24V","weight":"25kg","warranty":"1 year"}',
 12500000, NULL, 12, 'YW-D05', 0, 1, 45, 4.7, 12),
(1, 2, N'Máy đo huyết áp Beurer BM 26', 'beurer-bm26',
 N'Đo huyết áp và nhịp tim, màn hình màu, cảnh báo rối loạn nhịp.',
 N'{"display":"Color LCD","memory":"2x60","power":"4x AAA","warranty":"3 years"}',
 750000, 699000, 40, 'BEU-BM26', 0, 1, 190, 4.4, 28);

-- Product Images
INSERT INTO ProductImages (ProductId, ImageUrl, IsPrimary, SortOrder) VALUES
(1, 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&h=600&fit=crop', 1, 0),
(1, 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=600&fit=crop', 0, 1),
(2, 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&h=600&fit=crop', 1, 0),
(3, 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=600&h=600&fit=crop', 1, 0),
(4, 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=600&fit=crop', 1, 0),
(5, 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=600&h=600&fit=crop', 1, 0),
(6, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop', 1, 0),
(7, 'https://images.unsplash.com/photo-1597075095404-5cc8e96bfcf0?w=600&h=600&fit=crop', 1, 0),
(8, 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=600&fit=crop', 1, 0);

-- Coupons
INSERT INTO Coupons (Code, Description, DiscountType, DiscountValue, MinOrderAmount, MaxDiscount, UsageLimit, StartDate, EndDate) VALUES
('WELCOME10', N'Giảm 10% cho đơn đầu tiên', 'percent', 10, 500000, 200000, 1000, '2024-01-01', '2026-12-31'),
('MEDICARE50K', N'Giảm 50.000đ', 'fixed', 50000, 1000000, NULL, 500, '2024-01-01', '2026-12-31'),
('VIP15', N'Giảm 15% VIP', 'percent', 15, 2000000, 500000, 100, '2024-01-01', '2026-12-31');

-- Banners
INSERT INTO Banners (Title, Subtitle, ImageUrl, LinkUrl, SortOrder) VALUES
(N'Thiết bị y tế chính hãng', N'Cam kết 100% hàng chính hãng - Bảo hành đầy đủ', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1600&h=600&fit=crop', '/products', 1),
(N'Ưu đãi mùa hè', N'Giảm đến 30% máy đo huyết áp & đường huyết', 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=1600&h=600&fit=crop', '/products?category=may-do-huyet-ap', 2),
(N'Giao hàng toàn quốc', N'Freeship đơn từ 1 triệu - COD toàn quốc', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=1600&h=600&fit=crop', '/products', 3);

-- Testimonials
INSERT INTO Testimonials (CustomerName, Role, Content, Rating, SortOrder) VALUES
(N'Nguyễn Văn An', N'Bệnh viện tư nhân', N'MediCare Store cung cấp thiết bị chất lượng, giao hàng nhanh, hỗ trợ kỹ thuật tận tình.', 5, 1),
(N'Trần Thị Bình', N'Điều dưỡng', N'Tôi đã mua máy đo huyết áp Omron, sản phẩm chính hãng, giá tốt hơn nhiều nơi.', 5, 2),
(N'Lê Minh Cường', N'Khách hàng cá nhân', N'Website dễ sử dụng, thanh toán COD tiện lợi. Rất hài lòng với dịch vụ.', 5, 3),
(N'Phạm Thu Hà', N'Phòng khám', N'Đặt hàng số lượng lớn được chiết khấu, nhân viên tư vấn chuyên nghiệp.', 5, 4);

GO
